### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by rootameen** [stevebauman/maintenance-app#1]
Hello there!

I'm new to Lavarel, and I had lots of issues trying to install your app.
I'm installing this over apache in a virtual host:

1 | Performing the command: 

```
composer create-project stevebauman/maintenance --stability="dev"
```

installs maintenance in /us/local/bin/maintenance therefore I get no access to it though the web. 
That's why I specified the directory of public html.

The issue is that after installing and performing the second command in the same directory that I installed maintenance in:

```
php artisan maintenance:install
```

I get the error:

```
Status: 404 Not Found
X-Powered-By: PHP/5.4.39
Content-type: text/html

No input file specified.
```

2 |  So what I did is that I made a new folder and did an installation of lavarel/lavarel 4.0, and I can visit the /public page. but when I do your command:

```
composer create-project stevebauman/maintenance --stability="dev"
```

I get the error (with x as placeholder for actual location): 

```
[InvalidArgumentException]
  Project directory /x/x/public_html/ is not empty.
```

and when I try the second command, I get the error:

```
  [InvalidArgumentException]
  There are no commands defined in the "maintenance" namespace.
```

I'm pretty lost right now. So please help :cry:

**Comment by stevebauman** [comment]
Hi @rootAmeen! Thanks for contacting me.

Unfortunately this application is still in heavy development, and I'm working on several projects right now, single handedly. Updates are coming, but since I'm working on packages that this project relies on, those will come first, and then this will follow suit.

I apologize for this, but due to it's development status, I can't offer support when this application <b>will</b> be buggy, and currently has no release.

This application should be ready for at least an alpha release next month. I'll leave this issue open so I can update when it's available, and you will be notified about it.

**Comment by rootAmeen** [comment]
Looking forward for it.
